package com.fun.api.mapper;

import com.fun.api.domain.FxFriends;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface FxFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_friends
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_friends
     *
     * @mbggenerated
     */
    int insert(FxFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_friends
     *
     * @mbggenerated
     */
    int insertSelective(FxFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_friends
     *
     * @mbggenerated
     */
    FxFriends selectByPrimaryKey(Integer fxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_friends
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FxFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_friends
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FxFriends record);

    List<FxFriends> selectByUserId(Integer userId);
    FxFriends selectByKeyword(String keyword);
    FxFriends selectFriend(@Param("userId") Integer userId, @Param("friendId") Integer friendId);
    int deleteByIds(FxFriends record);
    int updateByIds(FxFriends record);
}