package com.fun.api.mapper;

import com.fun.api.domain.FxGroupInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface FxGroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_info
     *
     * @mbggenerated
     */
    int insert(FxGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_info
     *
     * @mbggenerated
     */
    int insertSelective(FxGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_info
     *
     * @mbggenerated
     */
    FxGroupInfo selectByPrimaryKey(Integer fxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FxGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(FxGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FxGroupInfo record);
}