package com.fun.api.mapper;

import com.fun.api.domain.FxGroupInfo;
import com.fun.api.domain.FxGroupUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface FxGroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fxId);
    int deleteByIds(@Param("groupId")Integer groupId,@Param("userId")Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_user
     *
     * @mbggenerated
     */
    int insert(FxGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_user
     *
     * @mbggenerated
     */
    int insertSelective(FxGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_user
     *
     * @mbggenerated
     */
    FxGroupUser selectByPrimaryKey(Integer fxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FxGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_group_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FxGroupUser record);

    int insertForeach(List<FxGroupUser> list);
    List<FxGroupUser> selectByGroupId(@Param("groupId")Integer groupId);
    FxGroupUser selectByIds(@Param("groupId")Integer groupId,@Param("userId")Integer userId);
    FxGroupUser selectExist(@Param("groupId")Integer groupId,@Param("userId")Integer userId);
    List<FxGroupUser> selectByGroupIdAndUserId(@Param("groupId")Integer groupId,@Param("userId")Integer userId);

    List<FxGroupInfo> selectByUserId(@Param("userId")Integer userId);

    int deleteByGroupId(@Param("groupId")Integer groupId);
}