package com.fun.api.mapper;

import com.fun.api.domain.FxUserInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FxUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user_info
     *
     * @mbggenerated
     */
    int insert(FxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user_info
     *
     * @mbggenerated
     */
    int insertSelective(FxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user_info
     *
     * @mbggenerated
     */
    FxUserInfo selectByPrimaryKey(Integer fxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FxUserInfo record);
    FxUserInfo selectByUserName(String phoneNo);
    FxUserInfo  searchUser(@Param("phoneNo") String phoneNo);
}