package com.fun.api.domain;

import java.util.Date;

public class FxAdminInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_admin_info.fx_id
     *
     * @mbggenerated
     */
    private Integer fxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_admin_info.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_admin_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_admin_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_admin_info.login_time
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_admin_info.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_admin_info.admin_auth
     *
     * @mbggenerated
     */
    private String adminAuth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_admin_info.fx_id
     *
     * @return the value of fx_admin_info.fx_id
     *
     * @mbggenerated
     */
    public Integer getFxId() {
        return fxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_admin_info.fx_id
     *
     * @param fxId the value for fx_admin_info.fx_id
     *
     * @mbggenerated
     */
    public void setFxId(Integer fxId) {
        this.fxId = fxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_admin_info.account
     *
     * @return the value of fx_admin_info.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_admin_info.account
     *
     * @param account the value for fx_admin_info.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_admin_info.password
     *
     * @return the value of fx_admin_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_admin_info.password
     *
     * @param password the value for fx_admin_info.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_admin_info.create_time
     *
     * @return the value of fx_admin_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_admin_info.create_time
     *
     * @param createTime the value for fx_admin_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_admin_info.login_time
     *
     * @return the value of fx_admin_info.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_admin_info.login_time
     *
     * @param loginTime the value for fx_admin_info.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_admin_info.state
     *
     * @return the value of fx_admin_info.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_admin_info.state
     *
     * @param state the value for fx_admin_info.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_admin_info.admin_auth
     *
     * @return the value of fx_admin_info.admin_auth
     *
     * @mbggenerated
     */
    public String getAdminAuth() {
        return adminAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_admin_info.admin_auth
     *
     * @param adminAuth the value for fx_admin_info.admin_auth
     *
     * @mbggenerated
     */
    public void setAdminAuth(String adminAuth) {
        this.adminAuth = adminAuth == null ? null : adminAuth.trim();
    }
}