package com.fun.api.domain;

public class FxFriends {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_friends.fx_id
     *
     * @mbggenerated
     */
    private Integer fxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_friends.user_id
     *
     * @mbggenerated
     */
    private Integer userId;
    private String nickName;
    private Integer isBlack;

    public Integer getIsBlack() {
        return isBlack;
    }

    public void setIsBlack(Integer isBlack) {
        this.isBlack = isBlack;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getAvatar() {
        return avatar;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_friends.friend_id
     *
     * @mbggenerated
     */
    private Integer friendId;
    private Integer userState;

    public Integer getUserState() {
        return userState;
    }

    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_friends.friend_remark
     *
     * @mbggenerated
     */
    private String friendRemark;
    private String avatar;

    public String avatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_friends.fx_id
     *
     * @return the value of fx_friends.fx_id
     *
     * @mbggenerated
     */
    public Integer getFxId() {
        return fxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_friends.fx_id
     *
     * @param fxId the value for fx_friends.fx_id
     *
     * @mbggenerated
     */
    public void setFxId(Integer fxId) {
        this.fxId = fxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_friends.user_id
     *
     * @return the value of fx_friends.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_friends.user_id
     *
     * @param userId the value for fx_friends.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_friends.friend_id
     *
     * @return the value of fx_friends.friend_id
     *
     * @mbggenerated
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_friends.friend_id
     *
     * @param friendId the value for fx_friends.friend_id
     *
     * @mbggenerated
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_friends.friend_remark
     *
     * @return the value of fx_friends.friend_remark
     *
     * @mbggenerated
     */
    public String getFriendRemark() {
        return friendRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_friends.friend_remark
     *
     * @param friendRemark the value for fx_friends.friend_remark
     *
     * @mbggenerated
     */
    public void setFriendRemark(String friendRemark) {
        this.friendRemark = friendRemark == null ? null : friendRemark.trim();
    }
}