package com.fun.api.domain;

import java.util.Date;

public class FxGroupInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_info.fx_id
     *
     * @mbggenerated
     */
    private Integer fxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_info.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_info.group_qr_code
     *
     * @mbggenerated
     */
    private String groupQrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_info.group_state
     *
     * @mbggenerated
     */
    private Integer groupState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_info.group_avatar
     *
     * @mbggenerated
     */
    private String groupAvatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_info.group_notice
     *
     * @mbggenerated
     */
    private String groupNotice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_info.fx_id
     *
     * @return the value of fx_group_info.fx_id
     *
     * @mbggenerated
     */
    public Integer getFxId() {
        return fxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_info.fx_id
     *
     * @param fxId the value for fx_group_info.fx_id
     *
     * @mbggenerated
     */
    public void setFxId(Integer fxId) {
        this.fxId = fxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_info.group_name
     *
     * @return the value of fx_group_info.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_info.group_name
     *
     * @param groupName the value for fx_group_info.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_info.group_qr_code
     *
     * @return the value of fx_group_info.group_qr_code
     *
     * @mbggenerated
     */
    public String getGroupQrCode() {
        return groupQrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_info.group_qr_code
     *
     * @param groupQrCode the value for fx_group_info.group_qr_code
     *
     * @mbggenerated
     */
    public void setGroupQrCode(String groupQrCode) {
        this.groupQrCode = groupQrCode == null ? null : groupQrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_info.group_state
     *
     * @return the value of fx_group_info.group_state
     *
     * @mbggenerated
     */
    public Integer getGroupState() {
        return groupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_info.group_state
     *
     * @param groupState the value for fx_group_info.group_state
     *
     * @mbggenerated
     */
    public void setGroupState(Integer groupState) {
        this.groupState = groupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_info.group_avatar
     *
     * @return the value of fx_group_info.group_avatar
     *
     * @mbggenerated
     */
    public String getGroupAvatar() {
        return groupAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_info.group_avatar
     *
     * @param groupAvatar the value for fx_group_info.group_avatar
     *
     * @mbggenerated
     */
    public void setGroupAvatar(String groupAvatar) {
        this.groupAvatar = groupAvatar == null ? null : groupAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_info.create_time
     *
     * @return the value of fx_group_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_info.create_time
     *
     * @param createTime the value for fx_group_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_info.update_time
     *
     * @return the value of fx_group_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_info.update_time
     *
     * @param updateTime the value for fx_group_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_info.group_notice
     *
     * @return the value of fx_group_info.group_notice
     *
     * @mbggenerated
     */
    public String getGroupNotice() {
        return groupNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_info.group_notice
     *
     * @param groupNotice the value for fx_group_info.group_notice
     *
     * @mbggenerated
     */
    public void setGroupNotice(String groupNotice) {
        this.groupNotice = groupNotice == null ? null : groupNotice.trim();
    }
}