package com.fun.api.domain;

import java.util.Date;

public class FxGroupUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_user.fx_id
     *
     * @mbggenerated
     */
    private Integer fxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_user.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;
    private String avatar;
    private String remark;

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_user.user_identity
     *
     * @mbggenerated
     */
    private Integer userIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_user.user_group_state
     *
     * @mbggenerated
     */
    private Integer userGroupState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_group_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_user.fx_id
     *
     * @return the value of fx_group_user.fx_id
     *
     * @mbggenerated
     */
    public Integer getFxId() {
        return fxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_user.fx_id
     *
     * @param fxId the value for fx_group_user.fx_id
     *
     * @mbggenerated
     */
    public void setFxId(Integer fxId) {
        this.fxId = fxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_user.group_id
     *
     * @return the value of fx_group_user.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_user.group_id
     *
     * @param groupId the value for fx_group_user.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_user.user_id
     *
     * @return the value of fx_group_user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_user.user_id
     *
     * @param userId the value for fx_group_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_user.user_identity
     *
     * @return the value of fx_group_user.user_identity
     *
     * @mbggenerated
     */
    public Integer getUserIdentity() {
        return userIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_user.user_identity
     *
     * @param userIdentity the value for fx_group_user.user_identity
     *
     * @mbggenerated
     */
    public void setUserIdentity(Integer userIdentity) {
        this.userIdentity = userIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_user.user_group_state
     *
     * @return the value of fx_group_user.user_group_state
     *
     * @mbggenerated
     */
    public Integer getUserGroupState() {
        return userGroupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_user.user_group_state
     *
     * @param userGroupState the value for fx_group_user.user_group_state
     *
     * @mbggenerated
     */
    public void setUserGroupState(Integer userGroupState) {
        this.userGroupState = userGroupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_user.create_time
     *
     * @return the value of fx_group_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_user.create_time
     *
     * @param createTime the value for fx_group_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_group_user.update_time
     *
     * @return the value of fx_group_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_group_user.update_time
     *
     * @param updateTime the value for fx_group_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}