package com.fun.api.domain;

import java.util.Date;

public class FxRequestState {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_request_state.fx_id
     *
     * @mbggenerated
     */
    private Integer fxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_request_state.request_id
     *
     * @mbggenerated
     */
    private Integer requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_request_state.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    private Date createTime;
    private String avatar;
    private String nickName;

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_request_state.request_state
     *
     * @mbggenerated
     */
    private Integer requestState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_request_state.request_msg
     *
     * @mbggenerated
     */
    private String requestMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_request_state.fx_id
     *
     * @return the value of fx_request_state.fx_id
     *
     * @mbggenerated
     */
    public Integer getFxId() {
        return fxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_request_state.fx_id
     *
     * @param fxId the value for fx_request_state.fx_id
     *
     * @mbggenerated
     */
    public void setFxId(Integer fxId) {
        this.fxId = fxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_request_state.request_id
     *
     * @return the value of fx_request_state.request_id
     *
     * @mbggenerated
     */
    public Integer getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_request_state.request_id
     *
     * @param requestId the value for fx_request_state.request_id
     *
     * @mbggenerated
     */
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_request_state.user_id
     *
     * @return the value of fx_request_state.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_request_state.user_id
     *
     * @param userId the value for fx_request_state.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_request_state.request_state
     *
     * @return the value of fx_request_state.request_state
     *
     * @mbggenerated
     */
    public Integer getRequestState() {
        return requestState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_request_state.request_state
     *
     * @param requestState the value for fx_request_state.request_state
     *
     * @mbggenerated
     */
    public void setRequestState(Integer requestState) {
        this.requestState = requestState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_request_state.request_msg
     *
     * @return the value of fx_request_state.request_msg
     *
     * @mbggenerated
     */
    public String getRequestMsg() {
        return requestMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_request_state.request_msg
     *
     * @param requestMsg the value for fx_request_state.request_msg
     *
     * @mbggenerated
     */
    public void setRequestMsg(String requestMsg) {
        this.requestMsg = requestMsg == null ? null : requestMsg.trim();
    }
}