package com.fun.api.domain;

import java.util.Date;

public class FxUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.fx_id
     *
     * @mbggenerated
     */
    private Integer fxId;
    private boolean friend;

    public boolean isFriend() {
        return friend;
    }

    public void setFriend(boolean friend) {
        this.friend = friend;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.fx_no
     *
     * @mbggenerated
     */
    private String fxNo;
    private Integer userState;

    public Integer getUserState() {
        return userState;
    }

    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.phone_no
     *
     * @mbggenerated
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.user_sex
     *
     * @mbggenerated
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.qr_code
     *
     * @mbggenerated
     */
    private String qrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.head_portrait_big
     *
     * @mbggenerated
     */
    private String headPortraitBig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.head_portrait_little
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.user_adress
     *
     * @mbggenerated
     */
    private String userAdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.signature
     *
     * @mbggenerated
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.create_ip
     *
     * @mbggenerated
     */
    private String createIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_user_info.user_money
     *
     * @mbggenerated
     */
    private Double userMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.fx_id
     *
     * @return the value of fx_user_info.fx_id
     *
     * @mbggenerated
     */
    public Integer getFxId() {
        return fxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.fx_id
     *
     * @param fxId the value for fx_user_info.fx_id
     *
     * @mbggenerated
     */
    public void setFxId(Integer fxId) {
        this.fxId = fxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.fx_no
     *
     * @return the value of fx_user_info.fx_no
     *
     * @mbggenerated
     */
    public String getFxNo() {
        return fxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.fx_no
     *
     * @param fxNo the value for fx_user_info.fx_no
     *
     * @mbggenerated
     */
    public void setFxNo(String fxNo) {
        this.fxNo = fxNo == null ? null : fxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.nick_name
     *
     * @return the value of fx_user_info.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.nick_name
     *
     * @param nickName the value for fx_user_info.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.password
     *
     * @return the value of fx_user_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.password
     *
     * @param password the value for fx_user_info.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.phone_no
     *
     * @return the value of fx_user_info.phone_no
     *
     * @mbggenerated
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.phone_no
     *
     * @param phoneNo the value for fx_user_info.phone_no
     *
     * @mbggenerated
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.user_sex
     *
     * @return the value of fx_user_info.user_sex
     *
     * @mbggenerated
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.user_sex
     *
     * @param userSex the value for fx_user_info.user_sex
     *
     * @mbggenerated
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.qr_code
     *
     * @return the value of fx_user_info.qr_code
     *
     * @mbggenerated
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.qr_code
     *
     * @param qrCode the value for fx_user_info.qr_code
     *
     * @mbggenerated
     */
    public void setQrCode(String qrCode) {
        this.qrCode = qrCode == null ? null : qrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.head_portrait_big
     *
     * @return the value of fx_user_info.head_portrait_big
     *
     * @mbggenerated
     */
    public String getHeadPortraitBig() {
        return headPortraitBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.head_portrait_big
     *
     * @param headPortraitBig the value for fx_user_info.head_portrait_big
     *
     * @mbggenerated
     */
    public void setHeadPortraitBig(String headPortraitBig) {
        this.headPortraitBig = headPortraitBig == null ? null : headPortraitBig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.head_portrait_little
     *
     * @return the value of fx_user_info.head_portrait_little
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.head_portrait_little
     *
     * @param avatar the value for fx_user_info.head_portrait_little
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.user_adress
     *
     * @return the value of fx_user_info.user_adress
     *
     * @mbggenerated
     */
    public String getUserAdress() {
        return userAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.user_adress
     *
     * @param userAdress the value for fx_user_info.user_adress
     *
     * @mbggenerated
     */
    public void setUserAdress(String userAdress) {
        this.userAdress = userAdress == null ? null : userAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.signature
     *
     * @return the value of fx_user_info.signature
     *
     * @mbggenerated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.signature
     *
     * @param signature the value for fx_user_info.signature
     *
     * @mbggenerated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.create_time
     *
     * @return the value of fx_user_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.create_time
     *
     * @param createTime the value for fx_user_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.create_ip
     *
     * @return the value of fx_user_info.create_ip
     *
     * @mbggenerated
     */
    public String getCreateIp() {
        return createIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.create_ip
     *
     * @param createIp the value for fx_user_info.create_ip
     *
     * @mbggenerated
     */
    public void setCreateIp(String createIp) {
        this.createIp = createIp == null ? null : createIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_user_info.user_money
     *
     * @return the value of fx_user_info.user_money
     *
     * @mbggenerated
     */
    public Double getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_user_info.user_money
     *
     * @param userMoney the value for fx_user_info.user_money
     *
     * @mbggenerated
     */
    public void setUserMoney(Double userMoney) {
        this.userMoney = userMoney;
    }
}